LocadoraDDD/LocadoraDDD.MVC/Models/LocacaoViewModel.cs
using LocadoraDDD.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LocadoraDDD.MVC.Models
{
    public class LocacaoViewModel
    {
        public int Id { get; set; }
        public string CpfCliente { get; set; }
        public DateTime DataLocacao { get; set; }

        public virtual ICollection<LocacaoFilmes> LocacaoFilmes { get; set; }
    }
}

LocadoraDDD/LocadoraDDD.MVC/Controllers/LocacaoController.cs
using AutoMapper;
using LocadoraDDD.Application.Interface;
using LocadoraDDD.Domain.Entities;
using LocadoraDDD.MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LocadoraDDD.MVC.Controllers
{
    [Authorize]
    public class LocacaoController : Controller
    {
        private readonly ILocacaoAppService _locacaoService;
        private readonly IFilmeAppService _filmeService;
        private readonly ILocacaoFilmesAppService _locFilmesService;

        public LocacaoController()
        {

        }

        public LocacaoController(ILocacaoAppService locacaoService, IFilmeAppService filmeService, ILocacaoFilmesAppService locFilmesService)
        {
            _locacaoService = locacaoService;
            _filmeService = filmeService;
            _locFilmesService = locFilmesService;
        }

        //ActionResult da homepage de locacao, trazendo a lista de locação já cadastrados.
        public ActionResult Index(string cpf = "")
        {
            var locacaos = Mapper.Map<IEnumerable<Locacao>, IEnumerable<LocacaoViewModel>>(_locacaoService.BuscarPorCpfCliente(cpf));
            ViewBag.Search = cpf;
            return View(locacaos);
        }


        //ActionResult para redirecionar para cadastro da locação.
        public ActionResult Cadastrar()
        {
            ViewBag.Filmes = _filmeService.GetAll();
            return View();
        }


        //ActionResult para salvar no banco a locação.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Cadastrar(LocacaoViewModel viewModel, List<int> idFilmes)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var locacao = Mapper.Map<Locacao>(viewModel);
                    locacao.DataLocacao = DateTime.Now;
                    _locacaoService.Add(locacao);

                    foreach (var item in idFilmes)
                    {
                        _locFilmesService.Add(new LocacaoFilmes
                        {
                            LocacaoId = locacao.Id,
                            FilmeId = item
                        });
                    }
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    throw;
                }
            }
            return View(viewModel);
        }

        //ActionResult para retornar os detalhes.
        public ActionResult Detalhes(int id)
        {
            var locacao = Mapper.Map<Locacao, LocacaoViewModel>(_locacaoService.GetById(id));

            List<Filme> listaFilmes = new List<Filme>();

            foreach (var item in locacao.LocacaoFilmes)
            {
                var filme = _filmeService.GetById(item.FilmeId);
                listaFilmes.Add(filme);
            }

            ViewBag.Filmes = listaFilmes;
            if (locacao == null)
            {
                return HttpNotFound();
            }
            return View(locacao);
        }

        //ActionResult que redireciona para edição da locação.
        public ActionResult Editar(int id)
        {
            var locacao = Mapper.Map<Locacao, LocacaoViewModel>(_locacaoService.GetById(id));
            if (locacao == null)
            {
                return HttpNotFound();
            }
            ViewBag.Filmes = _filmeService.GetAll();
            return View(locacao);
        }


        //ActionResult para atualizar no banco a locação.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(LocacaoViewModel viewModel, List<int> idFilmes)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    var locacao = Mapper.Map<Locacao>(viewModel);

                    if (idFilmes != null)
                    {
                        var locacaoFilmes = Mapper.Map<IEnumerable<LocacaoFilmes>>(_locFilmesService.GetAll().Where(lf => lf.LocacaoId == locacao.Id));
                        foreach(var loc in locacaoFilmes)
                        {
                            _locFilmesService.Remove(loc);
                        }
                        foreach (var item in idFilmes)
                        {

                            _locFilmesService.Add(new LocacaoFilmes
                            {
                                LocacaoId = locacao.Id,
                                FilmeId = item
                            });
                        }
                    }

                    _locacaoService.Update(locacao);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    throw;
                }
            }
            ViewBag.Filmes = _filmeService.GetAll();
            return View(viewModel);
        }

        //ActionResult para remover do banco a locação.

        public ActionResult Excluir(int id)
        {
            var locacao = Mapper.Map<LocacaoViewModel>(_locacaoService.GetById(id));
            if (locacao == null)
            {
                return HttpNotFound();
            }
            ViewBag.Filmes = _filmeService.GetAll();
            return View(locacao);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Excluir(LocacaoViewModel viewModel)
        {
            try
            {
                var locacao = Mapper.Map<Locacao>(viewModel);
                var locacaoFilmes = Mapper.Map<IEnumerable<LocacaoFilmes>>(_locFilmesService.GetAll().Where(lf => lf.LocacaoId == locacao.Id));
                foreach(var locFilmes in locacaoFilmes)
                {
                    _locFilmesService.Remove(locFilmes);
                }
                _locacaoService.Remove(locacao);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw;
            }
        }


        ////ActionResult para bloquear a locação.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Bloquear(int id)
        //{
        //    try
        //    {
        //        var locacao = Mapper.Map<Locacao>(_locacaoService.GetById(id));

        //        locacao.Ativo = false;
        //        _locacaoService.Update(locacao);
        //        return Json(new { ok = true });
        //    }
        //    catch (Exception ex)
        //    {
        //        return Json(new { ok = false });
        //    }

        //}

        ////ActionResult para desbloquear a locacao.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Liberar(int id)
        //{
        //    try
        //    {
        //        var locacao = Mapper.Map<Locacao>(_locacaoService.GetById(id));

        //        locacao.Ativo = true;
        //        _locacaoService.Update(locacao);
        //        return Json(new { ok = true });
        //    }
        //    catch (Exception ex)
        //    {
        //        return Json(new { ok = false });
        //    }

        //}
    }
}

LocadoraDDD/LocadoraDDD.MVC/Views/Locacao/Cadastrar.cshtml

@model LocadoraDDD.MVC.Models.LocacaoViewModel
@{
    ViewBag.Title = "Cadastrar";
}

<div class="container">
    <h2 style="padding-bottom: 20px;">Locações</h2>

    @using (Html.BeginForm("Cadastrar", "Locacao", FormMethod.Post, new { @Class = "form-horizontal" }))
    {
        <h4 style="padding-bottom: 10px;">Cadastrar novo gênero</h4>

        @Html.AntiForgeryToken()

        <div class="form-group">
            @Html.LabelFor(m => m.CpfCliente, new { @Class = "control-label col-md-1" })
            <div class="col-md-5">
                @Html.TextBoxFor(m => m.CpfCliente, new { @Class = "form-control cpf", placeholder = "000.000.000-00" })
                @Html.ValidationMessageFor(m => m.CpfCliente)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Filmes", new { @Class = "control-label col-md-1" })
            @foreach (var filme in ViewBag.Filmes)
            {
                <div class="col-md-5">
                    <input type="checkbox" name="idFilmes" value="@filme.Id" />
                    <span>@filme.Nome</span>
                </div>
            }
        </div>
        <button type="submit" class="btn btn-success" value="Cadastrar">Cadastrar Locação</button>
        <a href="@Url.Action("Index","Locacao")" class="btn btn-default"> Voltar</a>
    }
</div>

@section Scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.12/jquery.mask.js"></script>
    <script>
        $('.cpf').mask("000.000.000-00");
    </script>
}

LocadoraDDD/LocadoraDDD.MVC/Views/Locacao/Detalhes.cshtml

@model LocadoraDDD.MVC.Models.LocacaoViewModel

@{
    ViewBag.Title = "Detalhes";
}


<div class="container">
    <h1>Detalhes da Locação</h1>
    <p>Aqui você consegue visualizar os detalhes sobre a locação </p>

    <table class="table" style="margin-top: 20px;">
        <tbody>
            <tr>
                <td width="15%">Id</td>
                <td>@Model.Id</td>
            </tr>
            <tr>
                <td>Cpf do Cliente</td>
                <td>@Model.CpfCliente</td>
            </tr>
            <tr>
                <td>Data da Alocação</td>
                <td>@Model.DataLocacao</td>
            </tr>
            <tr>
                <td>Filmes Alocados</td>
                <td>
                    @foreach (var filme in ViewBag.Filmes)
                    {
                        <p>@filme.Nome</p>
                    }
                </td>
            </tr>
        </tbody>
    </table>
    <a href="@Url.Action("Index","Locacao")" class="btn btn-primary">Voltar</a>
</div>

LocadoraDDD/LocadoraDDD.MVC/Views/Locacao/Editar.cshtml
@model LocadoraDDD.MVC.Models.LocacaoViewModel
@{
    ViewBag.Title = "Editar";
}

    <div class="container">
        <h2>Locação Número @Model.Id</h2>

        @using (Html.BeginForm("Editar", "Locacao", FormMethod.Post, new { @Class = "form-horizontal" }))
        {
            <h4>Editar</h4>

            @Html.AntiForgeryToken()
            @Html.HiddenFor(m => m.DataLocacao)
            <div class="form-group">
                @Html.LabelFor(m => m.CpfCliente, new { @Class = "control-label col-md-1" })
                <div class="col-md-5">
                    @Html.TextBoxFor(m => m.CpfCliente, new { @Class = "form-control" })
                    @Html.ValidationMessageFor(m => m.CpfCliente)
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Filmes", new { @Class = "control-label col-md-1" })

                @foreach (var filme in ViewBag.Filmes)
                {
                    if (Model.LocacaoFilmes.Any(l => l.FilmeId == filme.Id))
                    {
                        <div class="col-md-5">
                            <input type="checkbox" name="idFilmes" value="@filme.Id" checked="checked" />
                            <span>@filme.Nome</span>
                        </div>
                    }
                    else
                    {
                        <div class="col-md-5">
                            <input type="checkbox" name="idFilmes" value="@filme.Id" />
                            <span>@filme.Nome</span>
                        </div>
                    }
                }
            </div>

            <div class="btn-group col-md-offset-1">
                <input type="submit" class="btn btn-success" value="Editar" style="margin-right: 10px;" />
                <a href="@Url.Action("Index")" class="btn btn-info">Voltar</a>
            </div>
        }
    </div>

LocadoraDDD/LocadoraDDD.MVC/Views/Locacao/Excluir.cshtml
@model LocadoraDDD.MVC.Models.LocacaoViewModel

@{
    ViewBag.Title = "Deletar";
}


<div class="container">
    <h1>Locação @Model.Id</h1>
    <p>Aqui você consegue visualizar os detalhes sobre a locação </p>

    @using (Html.BeginForm("Excluir", "Locacao", FormMethod.Post, new { @Class = "form-horizontal" }))
    {
        @Html.AntiForgeryToken()
        <table class="table" style="margin-top: 20px;">
            <tbody>
                <tr>
                    <td width="15%">Id</td>
                    <td>@Model.Id</td>
                </tr>
                <tr>
                    <td>Cpf do Cliente</td>
                    <td>@Model.CpfCliente</td>
                </tr>
                <tr>
                    <td>Data da Alocação</td>
                    <td>@Model.DataLocacao</td>
                </tr>
                <tr>
                    <td>Filmes Alocados</td>
                    <td>
                        @foreach (var filme in ViewBag.Filmes)
                        {
                            <p>@filme.Nome</p>
                        }
                    </td>
                </tr>
            </tbody>
        </table>
        <p> Tem certeza que quer deletar esse Registro? </p>
        <button type="submit" class="btn btn-warning">Excluir</button>
        <a href="@Url.Action("Index", "Locacao")" class="btn btn-primary">Voltar</a>
    }
</div>

LocadoraDDD/LocadoraDDD.MVC/Views/Locacao/Index.cshtml
@model IEnumerable<LocadoraDDD.MVC.Models.LocacaoViewModel>
@{
    ViewBag.Title = "Index";
}
<div class="container">
    <h1>Lista de Locações</h1>
    <p>Aqui você consegue visualizar As Locações Realizadas!</p>
    <div class="bloco" style="margin-top: 20px; margin-bottom: 70px;">
        <table class="fc-header" style="width: 100%;">
            <tbody>
                <tr style="height: 48px;">
                    <td class="fc-header-center" style="width:80%">
                        @using (Html.BeginForm("Index", "Locacao", FormMethod.Get))
                        {
                            <div class="row" style="padding-bottom: 20px;">
                                <div class="col-md-4">
                                    <input class="form-control" id="page" name="page" type="hidden" value="">
                                    <input class="form-control cpf" id="search" name="cpf" placeholder="Buscar por CPF" type="text" value="@ViewBag.Search">
                                </div>

                                <div class="col-md-2">
                                    <input type="submit" value="Buscar" class="btn bg-blue margin" style="margin: 0px; width: 100%;">
                                </div>
                            </div>}
                    </td>
                </tr>
            </tbody>
        </table>
        <p>
            <a href="@Url.Action("Cadastrar","Locacao")"><button class="btn btn-success"> Cadastrar Locação</button></a>
        </p>
    </div>
    <table class="table">
        <tr>
            <th>
                Id
            </th>

            <th>
                CPF do cliente
            </th>
            <th>
                Data de Locação
            </th>
            <th width="300">Ações</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.Id
                </td>
                <td>
                    @item.CpfCliente
                </td>
                <td>
                    @item.DataLocacao
                </td>
                <td>
                    <a href="@Url.Action("Editar","Locacao", new { id = item.Id})"><button class="btn btn-warning">Editar</button></a> |
                    <a href="@Url.Action("Detalhes","Locacao", new { id = item.Id})"><button class="btn btn-primary">Detalhes</button></a> |
                    <a href="@Url.Action("Excluir","Locacao", new { id = item.Id})"><button class="btn btn-danger">Excluir</button></a>
                </td>
            </tr>
        }

    </table>

</div>
@section scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.12/jquery.mask.js"></script>
    <script>
        $('.cpf').mask("000.000.000-00");
    </script>
}