LocadoraDDD/LocadoraDDD.MVC/Models/FilmeViewModel.cs
using LocadoraDDD.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LocadoraDDD.MVC.Models
{
    public class FilmeViewModel
    {
        public int Id { get; set; }

        public string Nome { get; set; }

        public DateTime DataCriacao { get; set; }
        public int GeneroId { get; set; }

        public bool Ativo { get; set; }

        public virtual GeneroViewModel Genero { get; set; }
    }
}

LocadoraDDD/LocadoraDDD.MVC/Controllers/FilmesController.cs
using AutoMapper;
using LocadoraDDD.Application.Interface;
using LocadoraDDD.Domain.Entities;
using LocadoraDDD.MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LocadoraDDD.MVC.Controllers
{
    [Authorize]
    public class FilmesController : Controller
    {
        private readonly IGeneroAppService _generoService;
        private readonly IFilmeAppService _filmeService;
        public FilmesController()
        {
        }


        public FilmesController(IFilmeAppService filmeService, IGeneroAppService generoService)
        {
            _filmeService = filmeService;
            _generoService = generoService;
        }

        //ActionResult da homepage de filmes, trazendo a lista de filmes já cadastrados.
        public ActionResult Index(string nome = "")
        {
            var filmes = Mapper.Map<IEnumerable<FilmeViewModel>>(_filmeService.BuscarPorTitulo(nome));
            ViewBag.Search = nome;
            return View(filmes);
        }


        //ActionResult para redirecionar para cadastro do filme.
        public ActionResult Cadastrar()
        {
            List<SelectListItem> listaGeneros = new List<SelectListItem>();

            listaGeneros.Add(new SelectListItem
            {
                Text = "Selecione...",
                Value = "0",
                Selected = true
            });

            var generos = Mapper.Map<IEnumerable<Genero>>(_generoService.GetAll());

            foreach (var genero in generos)
            {
                listaGeneros.Add(new SelectListItem
                {
                    Text = genero.Nome,
                    Value = genero.Id.ToString()
                });
            }

            ViewBag.Generos = listaGeneros;
            return View();
        }


        //ActionResult para salvar no banco o filme.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Cadastrar(FilmeViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    viewModel.DataCriacao = DateTime.Now;
                    var filme = Mapper.Map<Filme>(viewModel);
                    _filmeService.Add(filme);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    throw;
                }
            }
            return View(viewModel);
        }

        //ActionResult para retornar os detalhes.
        public ActionResult Detalhes(int id)
        {
            var filme = Mapper.Map<Filme, FilmeViewModel>(_filmeService.GetById(id));
            if (filme == null)
            {
                return HttpNotFound();
            }
            return View(filme);
        }

        //ActionResult que redireciona para edição do filme.
        public ActionResult Editar(int id)
        {

            List<SelectListItem> listaGeneros = new List<SelectListItem>();

            listaGeneros.Add(new SelectListItem
            {
                Text = "Selecione...",
                Value = "0",
                Selected = true
            });

            var generos = Mapper.Map<IEnumerable<Genero>>(_generoService.GetAll());

            foreach (var genero in generos)
            {
                listaGeneros.Add(new SelectListItem
                {
                    Text = genero.Nome,
                    Value = genero.Id.ToString()
                });
            }


            var filme = Mapper.Map<Filme, FilmeViewModel>(_filmeService.GetById(id));
            if (filme == null)
            {
                return HttpNotFound();
            }


            ViewBag.Generos = listaGeneros;
            return View(filme);
        }


        //ActionResult para atualizar no banco o filme.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(FilmeViewModel viewModel)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    var filme = Mapper.Map<Filme>(viewModel);
                    _filmeService.Update(filme);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    throw;
                }
            }
            return View(viewModel);
        }

        public ActionResult Excluir(int id)
        {
            var filme = Mapper.Map<FilmeViewModel>(_filmeService.GetById(id));
            if (filme == null)
            {
                return HttpNotFound();
            }
            return View(filme);
        }


        //ActionResult para remover do banco o filme.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Excluir(FilmeViewModel viewModel)
        {
            try
            {
                var filme = Mapper.Map<Filme>(viewModel);
                _filmeService.Remove(filme);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                throw;
            }
        }

        //ActionResult para remover múltiplos filmes do banco.
    
        public ActionResult ExcluirMultiplos(int[] idFilmes)
        {
            try
            {
                foreach (var id in idFilmes)
                {
                    var filme = Mapper.Map<Filme>(_filmeService.GetById(id));
                    _filmeService.Remove(filme);
                }
                return Json(new { ok = true });
            }
            catch (Exception e)
            {
                return Json(new { ok = false });
            }
        }



        //ActionResult para bloquear o filme.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Bloquear(int id)
        {
            try
            {
                var filme = Mapper.Map<Filme>(_filmeService.GetById(id));

                filme.Ativo = false;
                _filmeService.Update(filme);
                return Json(new { ok = true });
            }
            catch (Exception ex)
            {
                return Json(new { ok = false });
            }

        }

        //ActionResult para desbloquear o filme.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Liberar(int id)
        {
            try
            {
                var filme = Mapper.Map<Filme>(_filmeService.GetById(id));

                filme.Ativo = true;
                _filmeService.Update(filme);
                return Json(new { ok = true });
            }
            catch (Exception ex)
            {
                return Json(new { ok = false });
            }

        }

    }
}

LocadoraDDD/LocadoraDDD.MVC/Controllers/GeneroController.cs
using AutoMapper;
using LocadoraDDD.Application.Interface;
using LocadoraDDD.Domain.Entities;
using LocadoraDDD.MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LocadoraDDD.MVC.Controllers
{
    [Authorize]
    public class GeneroController : Controller
    {
        private readonly IGeneroAppService _generoService;

        public GeneroController()
        {

        }
        public GeneroController(IGeneroAppService generoService)
        {
            _generoService = generoService;
        }

        //ActionResult da homepage de gêneros, trazendo a lista de gêneros já cadastrados.
        public ActionResult Index(string name = "")
        {
            var generos = Mapper.Map<IEnumerable<Genero>, IEnumerable<GeneroViewModel>>(_generoService.BuscarPorTitulo(name));
            ViewBag.Search = name;
            return View(generos);
        }


        //ActionResult para redirecionar para cadastro do gênero.
        public ActionResult Cadastrar()
        {
            return View();
        }


        //ActionResult para salvar no banco o gênero.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Cadastrar(GeneroViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    viewModel.DataCriacao = DateTime.Now;
                    var genero = Mapper.Map<Genero>(viewModel);
                    _generoService.Add(genero);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    throw;
                }
            }
            return View(viewModel);
        }

        //ActionResult para retornar os detalhes.
        public ActionResult Detalhes(int id)
        {
            var genero = Mapper.Map<Genero, GeneroViewModel>(_generoService.GetById(id));
            if (genero == null)
            {
                return HttpNotFound();
            }
            return View(genero);
        }

        //ActionResult que redireciona para edição do gênero.
        public ActionResult Editar(int id)
        {
            var genero = Mapper.Map<Genero, GeneroViewModel>(_generoService.GetById(id));
            if (genero == null)
            {
                return HttpNotFound();
            }
            return View(genero);
        }


        //ActionResult para atualizar no banco o gênero.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(GeneroViewModel viewModel)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    var genero = Mapper.Map<Genero>(viewModel);
                    _generoService.Update(genero);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    throw;
                }
            }
            return View(viewModel);
        }


        [HttpGet]
        public ActionResult Excluir(int id)
        {
            var genero = Mapper.Map<GeneroViewModel>(_generoService.GetById(id));
            if (genero == null)
            {
                return HttpNotFound();
            }
            return View(genero);
        }

        //ActionResult para remover do banco o gênero.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Excluir(GeneroViewModel viewModel)
        {
            try
            {
                var genero = Mapper.Map<Genero>(viewModel);
                _generoService.Remove(genero);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        //ActionResult para remover múltiplos gêneros do banco.
        
        public ActionResult ExcluirMultiplos(int[] idGeneros)
        {
            try
            {
                foreach (var id in idGeneros)
                {
                    var genero = Mapper.Map<Genero>(_generoService.GetById(id));
                    _generoService.Remove(genero);
                }
                return Json(new { ok = true });
            }
            catch (Exception e)
            {
                return Json(new { ok = false });
            }
        }



        //ActionResult para bloquear o gênero.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Bloquear(int id)
        {
            try
            {
                var genero = Mapper.Map<Genero>(_generoService.GetById(id));

                genero.Ativo = false;
                _generoService.Update(genero);
                return Json(new { ok = true });
            }
            catch (Exception ex)
            {
                return Json(new { ok = false });
            }

        }

        //ActionResult para desbloquear o gênero.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Liberar(int id)
        {
            try
            {
                var genero = Mapper.Map<Genero>(_generoService.GetById(id));

                genero.Ativo = true;
                _generoService.Update(genero);
                return Json(new { ok = true });
            }
            catch (Exception ex)
            {
                return Json(new { ok = false });
            }

        }

    }
}

LocadoraDDD/LocadoraDDD.MVC/Views/Filmes/Cadastrar.cshtml
@model LocadoraDDD.MVC.Models.FilmeViewModel
@{
    ViewBag.Title = "Cadastrar";
}

    <div class="container">
        <h2 style="padding-bottom: 20px;">Films</h2>

        @using (Html.BeginForm("Cadastrar", "Filmes", FormMethod.Post, new { @Class = "form-horizontal" }))
        {
            <h4 style="padding-bottom: 10px;">Cadastrar novo filme</h4>

            @Html.AntiForgeryToken()

            <div class="form-group">
                @Html.LabelFor(m => m.Nome, new { @Class = "control-label col-md-1" })
                <div class="col-md-5">
                    @Html.TextBoxFor(m => m.Nome, new { @Class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Nome)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Genero, new { @Class = "control-label col-md-1" })
                <div class="col-md-5">

                    @Html.DropDownListFor(model => model.GeneroId, new SelectList(ViewBag.Generos, "Value", "Text"), new { @Class = "form-control" })
                    @Html.ValidationMessageFor(model => model.GeneroId)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Ativo, new { @Class = "control-label col-md-1" })
                <div class="col-md-5">
                    @Html.CheckBoxFor(m => m.Ativo)
                    @Html.ValidationMessageFor(m => m.Ativo)
                </div>
            </div>

            <button type="submit" class="btn btn-success" value="Cadastrar">Cadastrar Gênero</button>
            <a href="@Url.Action("Index","Genero")" class="btn btn-default"> Voltar</a>
        }
    </div>

LocadoraDDD/LocadoraDDD.MVC/Views/Filmes/Detalhes.cshtml

@model LocadoraDDD.MVC.Models.FilmeViewModel

@{
    ViewBag.Title = "Detalhes";
}


    <div class="container">
        <h1>Detalhes de @Model.Nome</h1>
        <p>Aqui você consegue visualizar os detalhes sobre o filme @Model.Nome</p>

        <table class="table" style="margin-top: 20px;">
            <tbody>
                <tr>
                    <td width="15%">Titulo</td>
                    <td>@Model.Nome</td>
                </tr>
                <tr>
                    <td>Data de cadastro</td>
                    <td>@Model.DataCriacao</td>
                </tr>
                <tr>
                    <td>Ativo</td>
                    <td>@(Model.Ativo? "Sim": "Não")</td>
                </tr>
                <tr>
                    <td>Gênero</td>
                    <td>@Model.Genero.Nome</td>
                </tr>
            </tbody>
        </table>
        <a href="@Url.Action("Editar","Filmes", new {id = Model.Id })" class="btn btn-warning">Editar filme</a>
        <a href="@Url.Action("Index","Filmes")" class="btn btn-primary">Voltar</a>
    </div>

LocadoraDDD/LocadoraDDD.MVC/Views/Filmes/Editar.cshtml
@model LocadoraDDD.MVC.Models.FilmeViewModel
@{
    ViewBag.Title = "Editar";
}

<div class="container">
    <h2>Filme @Model.Nome</h2>

    @using (Html.BeginForm("Editar", "Filmes", FormMethod.Post, new { @Class = "form-horizontal" }))
    {
        <h4>Editar</h4>

        @Html.AntiForgeryToken()
        @Html.HiddenFor(m => m.DataCriacao)

        <div class="form-group">
            @Html.LabelFor(m => m.Nome, new { @Class = "control-label col-md-1" })
            <div class="col-md-5">
                @Html.TextBoxFor(m => m.Nome, new { @Class = "form-control" })
                @Html.ValidationMessageFor(m => m.Nome)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Genero, new { @Class = "control-label col-md-1" })
            <div class="col-md-5">
                <select class="form-control" name="GeneroId">

                    @foreach (var option in ViewBag.Generos)
                    {
                        <option value="@option.Value" @(option.Value == Model.GeneroId.ToString() ? "selected=\"selected\"" : "")>@option.Text</option>
                    }
                </select>
                @Html.ValidationMessageFor(model => model.GeneroId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Ativo, new { @Class = "control-label col-md-1" })
            <div class="col-md-5">
                @Html.CheckBoxFor(m => m.Ativo)
                @Html.ValidationMessageFor(m => m.Ativo)
            </div>
        </div>

        <div class="btn-group col-md-offset-1">
            <input type="submit" class="btn btn-success" value="Editar" style="margin-right: 10px;" />
            <a href="@Url.Action("Index")" class="btn btn-info">Voltar</a>
        </div>
    }
</div>

LocadoraDDD/LocadoraDDD.MVC/Views/Filmes/Excluir.cshtml
@model LocadoraDDD.MVC.Models.FilmeViewModel

@{
    ViewBag.Title = "Deletar";
}


    <div class="container">
        <h1>Detalhes de @Model.Nome</h1>
        <p>Aqui você consegue visualizar os detalhes sobre o filme @Model.Nome</p>
        @using (Html.BeginForm("Excluir", "Filmes", FormMethod.Post, new { @Class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()
            <table class="table" style="margin-top: 20px;">
                <tbody>
                    <tr>
                        <td width="15%">Titulo</td>
                        <td>@Model.Nome</td>
                    </tr>
                    <tr>
                        <td>Data de cadastro</td>
                        <td>@Model.DataCriacao</td>
                    </tr>
                    <tr>
                        <td>Ativo</td>
                        <td>@(Model.Ativo ? "Sim" : "Não")</td>
                    </tr>
                    <tr>
                        <td>Gênero</td>
                        <td>@Model.Genero.Nome</td>
                    </tr>
                </tbody>
            </table>

            <p> Tem certeza que quer deletar esse Registro? </p>
            <button type="submit" class="btn btn-warning">Excluir</button>
            <a href="@Url.Action("Index", "Filmes")" class="btn btn-primary">Voltar</a>
        }
    </div>

LocadoraDDD/LocadoraDDD.MVC/Views/Filmes/Index.cshtml
@model IEnumerable<LocadoraDDD.MVC.Models.FilmeViewModel>


<div class="container">
    <h1>Lista de Filmes</h1>
    <p>Aqui você consegue visualizar nossa lista de filmes disponíveis!</p>
    <div class="bloco" style="margin-top: 20px; margin-bottom: 70px;">
        <table class="fc-header" style="width: 100%;">
            <tbody>
                <tr style="height: 48px;">
                    <td class="fc-header-center" style="width:80%">
                        @using (Html.BeginForm("Index", "Filmes", FormMethod.Get))
                        {
                            <div class="row" style="padding-bottom: 20px;">
                                <div class="col-md-4">
                                    <input class="form-control" id="page" name="page" type="hidden" value="">
                                    <input class="form-control" id="search" name="nome" placeholder="Busca" type="text" value="@ViewBag.Search">
                                </div>

                                <div class="col-md-2">
                                    <input type="submit" value="Buscar" class="btn bg-blue margin" style="margin: 0px; width: 100%;">
                                </div>
                            </div>}
                    </td>
                </tr>
            </tbody>
        </table>
        <p>
            <a href="@Url.Action("Cadastrar","Filmes")"><button class="btn btn-success"> Cadastrar Filme</button></a>
        </p>
    </div>
    <div class="bloco">

        <p style="text-align: right;">
            <button class="btn btn-primary" id="btn_multiple">Selecionar Vários</button>
            <button class="btn btn-primary" id="btn_remove_multiple" disabled="disabled">Remover Selecionados</button>

        </p>
    </div>
    <table class="table">
        <tr>
            <th width="150">
                Nome
            </th>
            <th>
                Data de Criação
            </th>
            <th>
                Gênero
            </th>
            <th>
                Ativo
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.Nome
                </td>
                <td>
                    @item.DataCriacao
                </td>
                <td>
                    @item.Genero.Nome
                </td>
                <td>
                    @(item.Ativo? "sim": "não")
                </td>
                <td style="text-align: center;">
                    <a href="@Url.Action("Editar","Filmes", new { id = item.Id})"><button class="btn btn-warning">Editar</button></a> |
                    <a href="@Url.Action("Detalhes","Filmes", new { id = item.Id})"><button class="btn btn-primary">Detalhes</button></a> |
                    <a href="@Url.Action("Excluir","Filmes", new { id = item.Id})"><button class="btn btn-danger">Excluir</button></a>
                    <input type="checkbox" class="check_multiple" value="@item.Id" name="idFilmes" style="display: none; margin-left:10px;" />
                </td>
            </tr>
        }

    </table>

</div>
@section Scripts{
    <script>
        var listaIds = new Array();
        $("#btn_multiple").click(function () {
            $('.check_multiple').toggle();
        });

        $('.check_multiple').click(function () {
            $(this).toggleClass("acionado");
            if ($(".acionado").length > 0 ) {
                $('#btn_remove_multiple').attr('disabled', false);
            } else {
                $('#btn_remove_multiple').attr('disabled', true);
            }
        });

        $('#btn_remove_multiple').click(function () {
            $('.check_multiple').each(function () {

                if ($(this).hasClass('acionado')) {
                    listaIds.push($(this).val());
                }
            })
            $.ajax({
                type: "POST",
                url: "@Url.Action("ExcluirMultiplos","Filmes")",
                data: { idFilmes: listaIds },
                success: function (data) {
                    if (data.ok) {
                        listaIds.splice(0, listaIds.length);
                        var confirmacao = confirm("Sucesso!");
                        if (confirmacao == true) {
                            window.location.reload();
                        }

                    } else {
                        listaIds.splice(0, listaIds.length);
                        confirm("Houve algum erro ao tentar remover o(s) registro(s)!");
                    }
                }
            })
        })


    </script>
}